### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = '../../Puma_Project/data/raw/T42_plasim_100y_10lay_scaled.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by ghost** [Cam-B04/Producing-realistic-climate-data-with-GANs#1]
Hi,

Could you please solve the issue ''OSError: Unable to open file (unable to open file: name = '../../Puma_Project/data/raw/T42_plasim_100y_10lay_scaled.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)''
Its looking for a file.
Thank you

**Comment by Cam-B04** [comment]
Hi ! 
It is now available on Kaggle website. You can find the download link in the new README.md. Please keep in mind that this is a largely reduced version of the dataset used in my article. 
Unfortunately, I have no longer access to the computational resources that I used during my PhD. 

Enjoy !
