### ISSUE TITLE
Output produced climate data

### ISSUE THREAD

**Issue by JCatwood** [Cam-B04/Producing-realistic-climate-data-with-GANs#3]
Hi,

I would like to raise a second issue regarding writing the simulated climate data into a file. Basically, I am thinking if I can use your code to train a model based on our climate data and write the simulated climate ensembles to a file.

It seems the code
```
wgan.train(epochs=5, save_interval=4, save_file='test',
           run_name='run_test', log_interval=10, log_file='test',
           data_generator=None, save_intermediate_model=True)
```
is able to train a `wgan` but I am wondering if I can run something like `wgan.simulate(<num_of_ensembles>, <output file name>)`.

Best regards,
Jian

**Comment by Cam-B04** [comment]
Hi @JCatwood , 

I am not sure to understand your question, if my reply does not answer what you asked do not hesitate to precise it. 

You definitely can train the GAN with your climate data. However it will be necessary to adapt the code a bit e.g. to the size of your data. 

About the writing of generated climate states to a file : 
  - If you want to write generated climate data to a file during the training to check if your training is converging for example it is already implemented. It is in `data/generated/<log_file>` where there is .npy files with 2 samples saved every <log_interval> training iteration. 
  - Another solution to visualize generated samples is to load the generator model which is also saved every log_interval iteration in the model folder. After loading it in a notebook for example, you can draw latent vectors (input vector of the generator) and pass it through the generator model to generate samples. 

Hope it helps.

**Comment by JCatwood** [comment]
Hi @Cam-B04,

Thank you very much for your reply. Sorry that I didn't express clearly what I would like to achieve with your code. I would like to generate samples from the trained GAN, which is essentially the Figure 9 in your paper https://npg.copernicus.org/articles/28/347/2021/.

Not sure how to modify the `training.py` file for this purpose.

Best regards,
Jian

**Comment by Cam-B04** [comment]
Thank you for the precision. 
To reproduce the figures from my article I recommend to use the jupyter notebooks by following these steps : 
  - In a terminal load the python environment created using the `requirement.txt` file. 
  - Go to the root of the repository : `cd /path/to/repo/producing-realistic-climate-data-with-GANs`
  - Start a jupyter notebook session using the command `jupyter notebook`, it should open directly a window in your browser, if not click the link in the terminal `http://localhost:XXXX...`
  - Finally, from the web browser open the file `Paper_figure_82c_GAN_training.ipynb` in the notebook folder by clicking on it.
  - Run the cells of the notebook to get the figure and understand how to produce fake samples. 

P.S. If you run the notebooks without a GPU these lines can throw an error you can comment them : 
`config = tf.ConfigProto()`
`config.gpu_options.per_process_gpu_memory_fraction = 0.8`
`config.gpu_options.allow_growth = True`
`#config.gpu_options.visible_device_list = str(3)`
`set_session(tf.Session(config=config))`

**Comment by JCatwood** [comment]
Thank you for your reply. The code organization looks clear but there is still one error when I was running `Paper_figure_82c_GAN_training.ipynb` that it reminded `No module named 'SpectralNormalizationKeras'`. I googled for the module briefly and found one repository here https://github.com/IShengFang/SpectralNormalizationKeras. Not sure if this is the module that should be used for your experiment.

Thanks,
Jian

**Comment by Cam-B04** [comment]
It should have been solved in my last commits. Can you try by pulling the latest version of the repo and retry to run the notebook ? 
For your information SpectralNormalizationKeras module is taken from the repository you mentioned and it should be imported from the `src/modeling/custom_classes.py script`. 
That is why the path is imported by `sys.path.append('../src/modeling/')` in the latest version of the notebooks.

**Comment by JCatwood** [comment]
Thank you so much for your explanation. I managed to produce fake samples from the notebook. However, when I tried using my own dataset to train a model, it seemed the `wg.WGANGP` had the dimensions of the training dataset hard-coded. Specifically, if I run:
```
X_train_test = np.random.rand(105, 60, 128, 81)

wgan = wg.WGANGP(latent_dim=64, target_shape=(60, 128, 81), batch_size=2,
                 optimizerG=None, optimizerC=None, summary=True, n_critic=1,
                 models=None, gradient_penalty=10, data=X_train_test[:100, :, :, :],
                 tfboard=False)
```
The program will output an error `ValueError: Operands could not be broadcast together with shapes (60, 128, 81) (64, 128, 81)`. If I change the `60` to `64`, the program works fine, i.e.,:
```
X_train_test = np.random.rand(105, 64, 128, 81)

wgan = wg.WGANGP(latent_dim=64, target_shape=(64, 128, 81), batch_size=2,
                 optimizerG=None, optimizerC=None, summary=True, n_critic=1,
                 models=None, gradient_penalty=10, data=X_train_test[:100, :, :, :],
                 tfboard=False)
```
May I ask if there is someway that I can do the model training with datasets (images) of dimensions different from 64 X 128?

**Comment by Cam-B04** [comment]
Yes you can but you have to change the architecture of the two networks inside the script. It requires little knowledge of the tensor flow/keras packages you can find lots of tutorial about it on the internet

**Comment by JCatwood** [comment]
Thank you very much for your help!
